PBR spotlight falloff
Moguri/panda3d-simplepbr pull request #31
Opened 2021-07-23 00:25 UTC by kukulski

implements spotlight falloff as defined at [pbr-book.org](https://www.pbr-book.org/3ed-2018/Light_Sources/Point_Lights#SpotLight::Falloff). It's _juuust slightly dirty_ in that it's smuggling the falloff angle (ok. the cos of the falloff angle) in by way of the existing panda3d spotlight exponent property, which... [wasn't supported by simplePBR anyway](https://github.com/Moguri/panda3d-simplepbr/issues/20).

<img width="537" alt="Screen Shot 2021-07-22 at 4 39 49 PM" src="https://user-images.githubusercontent.com/940674/126724481-6af0929d-c59c-44cd-a03e-ddd02de58556.png">

2021-08-05 22:59 UTC, Moguri requested changes
So, if I understand this correctly, `spotExponent` is just used as a way to pipe data in and no attempt is made to convert exponent values so a user can get reasonable responses to adjusting this value? I would prefer to avoid simplepbr-specifc trickery so it remains working as a drop-in replacement for Panda's auto shader.

2021-08-05 22:59 UTC, Moguri commented on simplepbr/shaders/simplepbr.frag
> +        float cosTheta = dot(normalize(p3d_LightSource[i].spotDirection), -l);
I would prefer that these didn't get renamed.

2021-08-06 06:03 UTC, rdb commented
Also see Moguri/panda3d-gltf#85 for how the glTF converter converts the outer distance into an exponent.  If you're going to use a linear falloff instead of an exponent, it should probably use the inverse of that calculation.

That said, is there a good reason not to just apply the exponent the way Panda does it here?

2021-09-13 20:37 UTC, kukulski commented
The awkward answer is "the systems I'm using Panda3d to prototype for all use inner-angle"

Longer answer: before switching to simplePBR, I'd done similar not-entirely-right work to set an exponent to approximate inner-angle. Later I accidentally discovered a side-effect where, in the regular pipeline, setting the _scale_ of a spotlight had an influence on the inner angle  `scale = 1/math.cos(math.radians(self.state.inner_angle))`, though setting exponent was still super wonky.  Later, while poking around to see if there was any chance of making area lights work, I found the place where I could make simplePBR do PBR-spec inner-angle, so that's what I did here. 

Is there a way to add uniforms to a light instance? If so, I can dispense with the dirty hack and make pbr-inner-angle cleanly opt-in.  (and maybe even figure out how to do area lights)

2023-05-08 23:41 UTC, Moguri commented
Closing due to inactivity

2023-05-08 23:41 UTC, closed without merging